services:
  samurai:
    build: .
    container_name: samurai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL:-sqlite+aiosqlite:////app/data/db.sqlite}
    volumes:
      - ./config.toml:/app/config.toml:ro
      - samurai_data:/app/data
      - ./ruspam_model/torch/model.safetensors:/app/ruspam_model/torch/model.safetensors:ro

volumes:
  samurai_data:
